fall_detection/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('server.urls')),
]

server/urls.py
from django.urls import path
import server.views as views

app_name = 'server'
urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('request/', views.get_requests, name='request'),
    path('cancelRequest/', views.cancelRequest, name='cancel-request'),
    path('confirmRequest/', views.confirmRequest, name='confirm-request'),
]

server/models.py
from django.db import models

class Admin(models.Model):
    id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=50, unique=True)
    password = models.CharField(max_length=100)

server/views.py
import json
from datetime import datetime

import requests
from django.http import JsonResponse
from django.shortcuts import render, redirect

from server.enities.patientRequest import PatientRequest
from server.models import Admin

project_id = 'falling-detection-3e200'
collection_register_patient = 'register-patient'
collection_user = 'user'
collection_user_device = 'user-device'
service_account_key_file = './falling-detection-3e200-firebase-adminsdk-bajkv-5e1cc2fe4a.json'


def home(request):
    if 'account' in request.session:
        return render(request, 'index.html')
    return redirect('server:login')


def login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        try:
            account = Admin.objects.get(username=username)
            if account.password == password:
                request.session['account'] = account.username
                return redirect('server:home')
            else:
                error_message = 'Tài khoản hoặc mật khẩu không đúng'
                return render(request, 'login.html', {'error_message': error_message})
        except Admin.DoesNotExist:
            error_message = 'Tài khoản hoặc mật khẩu không đúng'
            return render(request, 'login.html', {'error_message': error_message})
    else:
        return render(request, 'login.html')


def logout(request):
    if 'account' in request.session:
        del request.session['account']
    return redirect('server:login')


def get_requests(request):
    with open(service_account_key_file) as f:
        service_account_key = json.load(f)
        access_token = service_account_key["private_key"]

    url = f"https://firestore.googleapis.com/v1/projects/{project_id}/databases/(default)/documents/{collection_register_patient}?access_token={access_token}"

    response = requests.get(url)
    print(response.json())
    if response.status_code == 200:
        data = response.json()
        patientRequests = []
        for document in data.get('documents', []):
            fields = document.get('fields', {})
            fullName = fields.get('fullName', {}).get('stringValue')
            gender = fields.get('gender', {}).get('integerValue')
            date = fields.get('birthDate', {}).get('timestampValue')
            email = fields.get('email', {}).get('stringValue')
            phone = fields.get('phoneNumber', {}).get('stringValue')

            date_obj = datetime.fromisoformat(date[:-1])
            birthday = date_obj.date()
            patientRequest = PatientRequest(fullName, gender, birthday, email, phone)
            patientRequests.append(patientRequest)
        return render(request, 'request_list.html', {'patientRequests': patientRequests})
    else:
        print(f"Failed to retrieve data. Status code: {response.status_code}")
        return None


def deleteRequest(request):
    with open(service_account_key_file) as f:
        service_account_key = json.load(f)
        access_token = service_account_key["private_key"]
    email = request.GET.get('email')

    url = f"https://firestore.googleapis.com/v1/projects/{project_id}/databases/(default)/documents/{collection_register_patient}/{email}?access_token={access_token}"
    return requests.delete(url)


def cancelRequest(request):
    response = deleteRequest(request)
    if response.status_code == 200:
        return redirect('server:request')
    else:
        return None


def confirmRequest(request):
    with open(service_account_key_file) as f:
        service_account_key = json.load(f)
        access_token = service_account_key["private_key"]

    email = request.GET.get('email')
    deviceID = request.GET.get('deviceID')

    url = f"https://firestore.googleapis.com/v1/projects/{project_id}/databases/(default)/documents/{collection_user}?access_token={access_token}"
    response = requests.get(url)

    if response.status_code == 200:
        documents = response.json().get('documents', [])
        device_ids = set()

        for document in documents:
            fields = document.get('fields', {})
            existing_deviceID = fields.get('deviceID', {}).get('stringValue', None)
            if existing_deviceID:
                device_ids.add(existing_deviceID)
        if deviceID in device_ids:
            return JsonResponse({'error': 'Device ID already exists'}, status=400)

        url = f"https://firestore.googleapis.com/v1/projects/{project_id}/databases/(default)/documents/{collection_user}/{email}?updateMask.fieldPaths=deviceID&updateMask.fieldPaths=role&access_token={access_token}"

        request_body = {
            "fields": {
                "role": {
                    "integerValue": 1
                },
                "deviceID": {
                    "stringValue": deviceID
                }
            }
        }
        response = requests.patch(url, json=request_body)
        if response.status_code == 200:
            deleteRequest(request)
            return JsonResponse({'success': 'Add patient successfully'},status=200)
        else:
            print(f"Failed to update document. Status code: {response.status_code}")
            return JsonResponse({'error': 'Add patient failed'}, status=400)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Fall Dectection Server</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>

<body>
  <div class="flex">
    {% block content %} {% endblock %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
  </div>
</body>

</html>

templates/index.html
{% extends 'base.html' %} {% block content %}
<!-- Include the sidebar -->
{% include 'sidebar.html' %}

<!-- Your main content goes here -->
<!-- For example: -->
{% endblock %}

templates/login.html
{% extends 'base.html' %} {% block content %}

<div
  class="w-[100vw] h-[100vh] relative flex items-center justify-center"
>
  <div class="bg-gray-200 bg-opacity-80 w-[550px] rounded-lg py-12 px-12 z-50">
    <form method="post">
      {% csrf_token %}
      <div
        class="text-4xl uppercase text-center w-full text-orange-500 font-bold"
      >
        Đăng nhập
      </div>
      <div
        class="text-md text-red-500 text-center w-[100%] font-medium mt-2 min-h-[2rem] loginError"
      >
        {{ error_message }}
      </div>
      <div class="w-[100%] flex flex-col my-3">
        <label for="username" class="text-lg font-medium mb-1"
          >Tên tài khoản:
        </label>
        <input
          type="text"
          name="username"
          id="username"
          placeholder="Nhập tên tài khoản"
          class="text-lg rounded-md px-4 py-2 mb-1"
        />
      </div>
      <div class="w-[100%] flex flex-col my-3">
        <label for="password" class="text-lg font-medium mb-1"
          >Mật khẩu:
        </label>
        <input
          type="password"
          name="password"
          id="password"
          placeholder="Nhập mật khẩu"
          class="text-lg rounded-md px-4 py-2 mb-1"
        />
      </div>
      <div class="flex flex-row w-[100%] mt-3">
        <input
          type="submit"
          value="Đăng nhập"
          class="text-center text-lg mr-2 py-2 px-4 w-[100%] uppercase text-white bg-orange-500 hover:bg-orange-600 hover:cursor-pointer rounded-md font-semibold"
        />
      </div>
    </form>
  </div>
  <div class="absolute inset-0 backdrop-blur-xs backdrop-filter z-10"></div>
</div>

{% endblock %}

templates/request_list.html
{% extends 'base.html' %} {% block content %}
<!-- Include the sidebar -->
{% include 'sidebar.html' %}

<div class="flex-1 w-[80%] bg-orange-100">
    <div class="overflow-x-auto sm:mx-0.5 lg:mx-0.5">
        <div class="py-2 inline-block min-w-full sm:px-6 lg:px-8">
            <div class="overflow-hidden">
                <div class="flex flex-row justify-between items-center py-3 my-3 border-b-[2px] border-orange-400">
                    <div class="text-2xl text-orange-600 uppercase font-bold">
                        Patient Registration List
                    </div>
                </div>

                <div class="flex flex-row justify-between my-4">
                    <div class="flex bg-white px-3 py-2 rounded-md w-[300px]">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="gray" class="w-6 h-6">
                            <path fill-rule="evenodd"
                                d="M10.5 3.75a6.75 6.75 0 100 13.5 6.75 6.75 0 000-13.5zM2.25 10.5a8.25 8.25 0 1114.59 5.28l4.69 4.69a.75.75 0 11-1.06 1.06l-4.69-4.69A8.25 8.25 0 012.25 10.5z"
                                clip-rule="evenodd" />
                        </svg>
                        <input type="text" name="searchStudentId" id="search" placeholder="Enter name, email or phone"
                            class="flex-1 bg-white ml-2 outline-none" value="" />
                    </div>
                    <div class="flex items-center justify-center">
                        <span class="mr-2 font-normal text-base">Sort: </span>
                        <select class="min-w-[200px] rounded-md px-3 py-2" name="time">
                            <option value="0" selected>Latest</option>
                            <option value="1">Oldest</option>
                        </select>
                    </div>
                </div>
                {% if patientRequests %}
                <table class="min-w-full">
                    <thead class="bg-white border-b">
                        <tr>
                            <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-center">
                                STT
                            </th>
                            <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-center">
                                Fullname
                            </th>
                            <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-center">
                                Gender
                            </th>
                            <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-center">
                                Birthday
                            </th>
                            <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-center">
                                Email
                            </th>
                            <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-center">
                                Phone
                            </th>
                            <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-center">
                                Status
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for patientRequest in patientRequests %}
                        {% if forloop.counter|divisibleby:2 %}
                        <tr class="bg-white-200 border-b">
                            {% else %}
                        <tr class="bg-orange-200 border-b">
                            {% endif %}
                            <td class="px-6 py-4 whitespace-nowrap text-center text-sm font-normal text-gray-900">
                                {{ forloop.counter }}
                            </td>
                            <td class="px-6 py-4 whitespace-nowrap text-center text-sm font-normal text-gray-900">
                                {{ patientRequest.fullName }}
                            </td>
                            <td class="px-6 py-4 whitespace-nowrap text-center text-sm font-normal text-gray-900">
                                {% if patientRequest.gender == 1 %}
                                    <p>Male</p>
                                {% else %}
                                    <p>Female</p>
                                {% endif %}
                            </td>
                            <td class="px-6 py-4 whitespace-nowrap text-center text-sm font-normal text-gray-900">
                                {{ patientRequest.birthday|date:"d-m-Y" }}
                            </td>
                            <td class="px-6 py-4 whitespace-nowrap text-center text-sm font-normal text-gray-900">
                                {{ patientRequest.email }}
                            </td>
                            <td class="px-6 py-4 whitespace-nowrap text-center text-sm font-normal text-gray-900">
                                {{ patientRequest.phone }}
                            </td>
                            <td class="text-sm text-gray-900 font-normal px-6 py-4 whitespace-nowrap text-center">
                                <a href="{% url 'server:cancel-request' %}?email={{ patientRequest.email }}" class="px-2 py-1 text-sm font-medium bg-gray-400 text-white rounded-lg hover:cursor-pointer hover:bg-gray-500">Cancel</a>
                                <a class="px-2 py-1 text-sm font-medium bg-orange-400 text-white rounded-lg hover:cursor-pointer hover:bg-orange-500" data-bs-toggle="modal" data-bs-target="#exampleModal">Confirm</a>
                            </td>
                        </tr>
                            <!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Device ID</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <input id="email" class="w-[100%] hidden" type="text" name="email" value="{{ patientRequest.email }}"/>
        <input id="deviceID" class="w-[100%] focus:border-none" type="text" name="deviceID" placeholder="Enter device ID"/>
          <div
        class="text-md text-red-500 text-center w-[100%] font-medium mt-2 min-h-[2rem] error"
      >
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-warning confirm-button" data-bs-email="{{ patientRequest.email }}">Confirm</button>
      </div>
    </div>
  </div>
</div>
                        {% endfor %}
                    </tbody>
                </table>
                {% else %}
                <div class="text-xl text-orange-400 font-bold">No request found</div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
<script>
document.addEventListener('DOMContentLoaded', function () {
    const confirmButton = document.querySelector('.confirm-button');
    const errorDiv = document.querySelector('.modal-body .error');

    confirmButton.addEventListener('click', function () {
        const email = document.getElementById('email').value;
        const deviceID = document.getElementById('deviceID').value;

        fetch(`/confirmRequest?email=${email}&deviceID=${deviceID}`, {
            method: 'GET',
            headers: {
                'Content-Type': 'application/json'
            }
        })
        .then(response => response.json())
        .then(data => {
            if (data.error) {
                errorDiv.textContent = data.error;
            } else {
                window.location.href = '/request';
                errorDiv.textContent = '';
                // Optionally, you can close the modal or perform another action on success
                alert('Device ID confirmed successfully.');
                // You can close the modal or redirect the user here
            }
        })
        .catch(error => {
            errorDiv.textContent = 'An error occurred. Please try again.';
        });
    });
});
</script>
{% endblock %}

templates/sidebar.html
{% load static %}
<div class="w-[280px] bg-orange-300 flex flex-col items-center justify-start h-[100vh]">
  <img src="/static/img/Fall-Detection.png" class="w-[120px] h-[120px] rounded-2xl my-4"  alt="fall-img"/>
  <div class="text-center text-sm mb-6">
    <div>You are logging in as</div>
    <div class="font-medium text-orange-700">{{ request.session.account }}</div>
  </div>
  {% if not request.session.is_student %}
  <ul class="w-full px-6 flex-1">
    <li
      class="w-full flex items-center text-left my-2 px-2 py-1 hover:bg-orange-400 hover:rounded-lg hover:text-orange-100 hover:cursor-pointer">
      <a href="{% url 'server:request' %}" class="flex flex-row">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-7 h-7">
          <path fill-rule="evenodd"
            d="M7.502 6h7.128A3.375 3.375 0 0118 9.375v9.375a3 3 0 003-3V6.108c0-1.505-1.125-2.811-2.664-2.94a48.972 48.972 0 00-.673-.05A3 3 0 0015 1.5h-1.5a3 3 0 00-2.663 1.618c-.225.015-.45.032-.673.05C8.662 3.295 7.554 4.542 7.502 6zM13.5 3A1.5 1.5 0 0012 4.5h4.5A1.5 1.5 0 0015 3h-1.5z"
            clip-rule="evenodd" />
          <path fill-rule="evenodd"
            d="M3 9.375C3 8.339 3.84 7.5 4.875 7.5h9.75c1.036 0 1.875.84 1.875 1.875v11.25c0 1.035-.84 1.875-1.875 1.875h-9.75A1.875 1.875 0 013 20.625V9.375zM6 12a.75.75 0 01.75-.75h.008a.75.75 0 01.75.75v.008a.75.75 0 01-.75.75H6.75a.75.75 0 01-.75-.75V12zm2.25 0a.75.75 0 01.75-.75h3.75a.75.75 0 010 1.5H9a.75.75 0 01-.75-.75zM6 15a.75.75 0 01.75-.75h.008a.75.75 0 01.75.75v.008a.75.75 0 01-.75.75H6.75a.75.75 0 01-.75-.75V15zm2.25 0a.75.75 0 01.75-.75h3.75a.75.75 0 010 1.5H9a.75.75 0 01-.75-.75zM6 18a.75.75 0 01.75-.75h.008a.75.75 0 01.75.75v.008a.75.75 0 01-.75.75H6.75a.75.75 0 01-.75-.75V18zm2.25 0a.75.75 0 01.75-.75h3.75a.75.75 0 010 1.5H9a.75.75 0 01-.75-.75z"
            clip-rule="evenodd" />
        </svg>
        <span class="ml-4 text-xl font-medium">Patient Register</span>
      </a>
    </li>
    <li
      class="w-full flex items-center text-left my-2 px-2 py-1 hover:bg-orange-400 hover:rounded-lg hover:text-orange-100 hover:cursor-pointer">
      <a href="" class="flex flex-row">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-7 h-7">
          <path fill-rule="evenodd"
            d="M18.685 19.097A9.723 9.723 0 0021.75 12c0-5.385-4.365-9.75-9.75-9.75S2.25 6.615 2.25 12a9.723 9.723 0 003.065 7.097A9.716 9.716 0 0012 21.75a9.716 9.716 0 006.685-2.653zm-12.54-1.285A7.486 7.486 0 0112 15a7.486 7.486 0 015.855 2.812A8.224 8.224 0 0112 20.25a8.224 8.224 0 01-5.855-2.438zM15.75 9a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0z"
            clip-rule="evenodd" />
        </svg>
        <span class="ml-4 text-xl font-medium">Account</span>
      </a>
    </li>
  </ul>
  {% endif %}
  <a href="{% url 'server:logout' %}" class="text-base font-medium text-orange-600 my-2 hover:text-orange-800">Logout</a>
</div>